blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djangogirls.urls')),
    path('polls/', include('djangopolls.urls')),
    path('api/v1/', include('restapi.urls')),
]

admin.site.site_header = 'BLOG ADMIN'
admin.site.index_title = "Welcome to Blog Portal"

djangopolls/urls.py
from django.urls import path
from djangopolls.views import  results, vote, detail, index

app_name = "polls"
urlpatterns = [
    path("index/", index, name="homepage"),
    path("<str:slug>/", detail, name="detail"),
    path("<int:question_id>/vote/", vote, name="vote"),
    path("<int:question_id>/results/", results, name="results"),
]

djangopolls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    slug = models.SlugField(max_length = 200, unique=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


    def was_published_recently(self):
        now = timezone.now()
        return (now - datetime.timedelta(days=1)) <= (self.pub_date <= now)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text    

djangopolls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from djangopolls.models import Question, Choice
from django.http import Http404
from django.urls import reverse

# Create your views here.


def detail(request, slug):
    try:
        question = Question.objects.get(slug=slug)
    except Question.DoesNotExist:
        raise Http404(' Question Does Not exist')
    question = get_object_or_404(Question, slug=slug)
    return render(request, "polls/detail.html", {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
        print('post method :', request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "You didn't select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def index(request):
    question = Question.objects.all()
    return render(request, "polls/index.html", {'question': question})

djangopolls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/djangogirls.css' %}">
    <title>Blog</title>
</head>

<body>
    <header class="page-header">
        <div class="container d-flex">
            <h1><a href="/">Django Girls Blog<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <h1><a href="{% url 'polls:homepage' %}">Django polls<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            {% if user.is_authenticated %}
            <h1><a href="{% url 'userprofileview' %}">{{user.first_name}}<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <h1><a href="{% url 'userlogout' %}">logout<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <h1><a href="{% url 'post_new' %}">Create Post<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            {% else %}

            <h1><a href="{% url 'register' %}">register<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <h1><a href="{% url 'login' %}">login<a></h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            {% endif %}
        </div>
    </header>
    <main class="container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

djangopolls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_massage %}<p><strong>{{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
</form>
{% endblock %}

djangopolls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
    {%if latest_question_list %}
    <ul>
        {% for q in latest_question_list %}
        <li><a href="{% url 'polls:detail' q.slug %}">{{ q.question_text }}</a></li>
        {% endfor %}
    </ul>
    
    {% endif %}

    <ul>
       {% for q in question %}
        <li><a href="{% url 'polls:detail' q.slug %}">{{ q.question_text }}</a></li>
       {% endfor %}
    </ul>
{% endblock %}

djangopolls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.slug %}">Vote again?</a>
{% endblock %}